# Generated by Django 2.1.7 on 2019-03-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieces',
            name='link',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='series',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='text',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='title',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
