# Generated by Django 2.1.7 on 2019-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190328_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieces',
            name='id',
        ),
        migrations.AlterField(
            model_name='pieces',
            name='title',
            field=models.CharField(default='n/a', max_length=200, primary_key=True, serialize=False),
        ),
    ]
