# Generated by Django 2.1.7 on 2019-04-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190402_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieces',
            name='id',
            field=models.CharField(default='n/a', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='title',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
