# Generated by Django 2.1.7 on 2019-04-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190402_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='title',
            field=models.CharField(default='n/a', max_length=201),
        ),
    ]
