# Generated by Django 2.1.7 on 2019-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190402_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='title',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
