# Generated by Django 2.1.7 on 2019-04-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190403_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieces',
            options={'verbose_name_plural': 'Pieces'},
        ),
        migrations.AlterField(
            model_name='pieces',
            name='series',
            field=models.IntegerField(default='0'),
        ),
    ]
