# Generated by Django 2.1.7 on 2019-04-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190403_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='id',
            field=models.IntegerField(default='9999', primary_key=True, serialize=False),
        ),
    ]
