# Generated by Django 2.1.7 on 2019-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190404_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieces',
            name='series_name',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
